defaults: &defaults
  docker:
    - image: circleci/node:10-stretch
  working_directory: ~/repo

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6-stretch
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
